<a href="https://colab.research.google.com/github/dangtrantrung/Deep_Learning_PyTorch_with_Google_Colab/blob/master/Deep_Learning_PyTorch_with_Google_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch


// thay thế numpy

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [3]:
x=torch.empty(5,3)
x

tensor([[-5.0679e+11,  4.5573e-41, -5.4893e+01],
        [ 3.2938e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [4]:
y=torch.rand(5,3)
y

tensor([[0.5753, 0.3840, 0.8127],
        [0.4136, 0.1197, 0.4693],
        [0.8284, 0.9200, 0.8213],
        [0.3613, 0.0283, 0.8999],
        [0.6654, 0.9694, 0.4531]])

In [5]:
zero=torch.zeros(5,3,dtype=torch.long)
zero

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
tensor_randn_like=torch.randn_like(x, dtype=torch.double)
tensor_randn_like

tensor([[ 0.8984,  0.4050,  1.2070],
        [ 0.8515, -1.3542,  0.3844],
        [ 0.9644, -0.6292, -1.1892],
        [ 0.7818,  1.2881, -0.1233],
        [-0.0448, -0.5233, -0.3932]], dtype=torch.float64)

In [7]:
tensor_randn_like.shape

torch.Size([5, 3])

In [8]:
k=x+tensor_randn_like
k

tensor([[-5.0679e+11,  4.0501e-01, -5.3686e+01],
        [ 8.5149e-01, -1.3542e+00,  3.8436e-01],
        [ 9.6442e-01, -6.2925e-01, -1.1892e+00],
        [ 7.8181e-01,  1.2881e+00, -1.2328e-01],
        [-4.4836e-02, -5.2332e-01, -3.9324e-01]], dtype=torch.float64)

In [9]:
h=torch.add(x,y)
h

tensor([[-5.0679e+11,  3.8395e-01, -5.4080e+01],
        [ 4.1361e-01,  1.1965e-01,  4.6930e-01],
        [ 8.2842e-01,  9.2004e-01,  8.2134e-01],
        [ 3.6131e-01,  2.8347e-02,  8.9988e-01],
        [ 6.6542e-01,  9.6937e-01,  4.5310e-01]])

In [10]:
# c=a+b
a=torch.rand(4,4)
b=torch.rand(4,4)
c=torch.empty(4,4)
torch.add(a,b,out=c)
c

tensor([[0.5676, 0.6501, 1.4943, 0.4873],
        [1.2084, 0.7240, 1.2700, 1.1547],
        [1.2704, 1.5644, 1.1425, 1.0434],
        [0.6232, 1.8900, 0.7002, 0.5725]])

In [11]:
a[:,1]
a[:,2]

tensor([0.5722, 0.5584, 0.8624, 0.1347])

In [12]:
a[:,3]

tensor([0.4713, 0.1768, 0.8536, 0.5570])

In [13]:
a[0:3,1:2]

tensor([[0.2994],
        [0.2100],
        [0.8674]])

In [14]:
view=a.view(16)

In [15]:
view.shape

torch.Size([16])

In [16]:
y=a.view(-1,8)
y

tensor([[0.4351, 0.2994, 0.5722, 0.4713, 0.9250, 0.2100, 0.5584, 0.1768],
        [0.8130, 0.8674, 0.8624, 0.8536, 0.0095, 0.9064, 0.1347, 0.5570]])

In [17]:
one=torch.randn(1)
one

tensor([1.1874])

In [18]:
a=np.ones(3)
a

array([1., 1., 1.])

In [19]:
b=torch.from_numpy(a)
b

tensor([1., 1., 1.], dtype=torch.float64)

In [20]:
# if device has GPU - T4 GPU - CPU or TPU
device=torch.cuda.is_available()
device

False

In [21]:
#x.cpu() chuyển về tính toán trên CPU không tính trên TGPU hay TPU
b.cpu()

tensor([1., 1., 1.], dtype=torch.float64)

In [22]:
# các hàm trên tensor
# lưu thông tin gradient, function_fn đã sử dụng của tensor
# backward: đạo hàm
# grad: lưu thông tin đạo hàm của tensor
x=torch.tensor(2.0,requires_grad=True)
x

tensor(2., requires_grad=True)

In [23]:
y=torch.exp(x)
y

tensor(7.3891, grad_fn=<ExpBackward0>)

In [24]:
y.backward(retain_graph=True)
x.grad

tensor(7.3891)

### Build Model NN

In [26]:
import torch.nn as nn
import torch.nn.functional as F


In [27]:
class Net(nn.Module):
  def __init__(self):
    super(Net,self).__init__()
    # 5 layers
    self.conv1=nn.Conv2d(1,6,3)
    self.conv2=nn.Conv2d(6,16,3)
    self.fc1=nn.Linear(16*6*6,120)
    self.fc2=nn.Linear(120,84)
    self.fc3=nn.Linear(84,10)

    # forward, kernel w*h
    # 1,2
    # 3,4 max+pool2d =>4 in kernel 2x2
  def forward(self,x):
    x=self.conv1(x)
    x=F.max_pool2d(x,(2,2))
