<a href="https://colab.research.google.com/github/dangtrantrung/Deep_Learning_PyTorch_with_Google_Colab/blob/master/Deep_Learning_PyTorch_with_Google_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [3]:
x=torch.empty(5,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
y=torch.rand(5,3)
y

tensor([[0.3193, 0.1840, 0.9009],
        [0.1442, 0.9378, 0.9120],
        [0.8457, 0.0022, 0.4492],
        [0.8518, 0.6167, 0.5124],
        [0.9868, 0.7307, 0.1729]])

In [5]:
zero=torch.zeros(5,3,dtype=torch.long)
zero

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])