<a href="https://colab.research.google.com/github/dangtrantrung/Deep_Learning_PyTorch_with_Google_Colab/blob/master/Deep_Learning_PyTorch_with_Google_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

// thay thế numpy

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [3]:
x=torch.empty(5,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
y=torch.rand(5,3)
y

tensor([[0.6862, 0.5167, 0.4823],
        [0.8387, 0.2289, 0.3370],
        [0.1086, 0.1640, 0.6589],
        [0.9203, 0.4836, 0.1194],
        [0.9207, 0.9917, 0.2382]])

In [5]:
zero=torch.zeros(5,3,dtype=torch.long)
zero

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
tensor_randn_like=torch.randn_like(x, dtype=torch.double)
tensor_randn_like

tensor([[-0.3433,  0.3863,  0.3138],
        [ 0.8266,  0.1972,  0.6965],
        [ 0.1066, -0.5767,  0.0899],
        [-1.5566, -0.9251, -1.4881],
        [ 0.2047, -1.7453,  0.4417]], dtype=torch.float64)

In [7]:
tensor_randn_like.shape

torch.Size([5, 3])

In [8]:
k=x+tensor_randn_like
k

tensor([[-0.3433,  0.3863,  0.3138],
        [ 0.8266,  0.1972,  0.6965],
        [ 0.1066, -0.5767,  0.0899],
        [-1.5566, -0.9251, -1.4881],
        [ 0.2047, -1.7453,  0.4417]], dtype=torch.float64)

In [9]:
h=torch.add(x,y)
h

tensor([[0.6862, 0.5167, 0.4823],
        [0.8387, 0.2289, 0.3370],
        [0.1086, 0.1640, 0.6589],
        [0.9203, 0.4836, 0.1194],
        [0.9207, 0.9917, 0.2382]])

In [10]:
# c=a+b
a=torch.rand(4,4)
b=torch.rand(4,4)
c=torch.empty(4,4)
torch.add(a,b,out=c)
c

tensor([[0.7952, 0.7526, 1.5742, 1.1548],
        [1.1334, 0.6883, 1.2030, 0.5486],
        [1.2593, 1.6037, 1.3680, 0.7058],
        [1.0974, 1.6470, 0.2847, 1.3393]])

In [11]:
a[:,1]
a[:,2]

tensor([0.8295, 0.4297, 0.7592, 0.0598])

In [12]:
a[:,3]

tensor([0.4893, 0.1020, 0.5965, 0.6092])

In [13]:
a[0:3,1:2]

tensor([[0.3427],
        [0.2799],
        [0.6217]])

In [14]:
view=a.view(16)

In [15]:
view.shape

torch.Size([16])

In [16]:
y=a.view(-1,8)
y

tensor([[0.7147, 0.3427, 0.8295, 0.4893, 0.9625, 0.2799, 0.4297, 0.1020],
        [0.4748, 0.6217, 0.7592, 0.5965, 0.5519, 0.8963, 0.0598, 0.6092]])